version: '3'

services:
    server:
        image: ghcr.io/drakeapps/mqtt-433mhz-outlet
        privileged: true
        restart: always
        volumes:
            - ./config/:/usr/src/app/config
        command: "node mqtt.js --mqttHost ${MQTTHOST}"
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
    sniffer:
        image: ghcr.io/drakeapps/mqtt-433mhz-outlet
        privileged: true
        command: "/usr/src/app/433Utils/RPi_utils/RFSniffer"
    
